# Generated by Django 3.1.4 on 2021-01-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('idUser', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dateOfBirth', models.CharField(max_length=255)),
                ('placeOfBirth', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('idTrip', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tripName', models.CharField(max_length=255)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('startDate', models.CharField(max_length=16)),
                ('endDate', models.CharField(max_length=16)),
                ('departure', models.CharField(max_length=255)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Trip_User', to='Tripplaner.account')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('idExpense', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('expenseName', models.CharField(max_length=255)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('idTrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Expense_Trip', to='Tripplaner.trip')),
            ],
        ),
    ]
