# Generated by Django 3.1.4 on 2021-01-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tripplaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='typeExpense',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
