# Generated by Django 3.1.4 on 2021-01-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tripplaner', '0004_auto_20210115_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('idTrip', 'idUser')},
        ),
    ]
